name: Kubectl set cronjob suspend
description: Set cronjob suspend
author: Tomas Hulata <thulata@pixelfederation.com>
runs:
  using: node12
  main: main.js
inputs:
  directory:
    description: Working directory
    required: false
    default: "."
  namespace:
    description: K8s namespace to use
    required: true
  regexp:
    description: Regexp prefix to match cronjob without cronjob name
    required: true
  kubeconfig:
    description: Path to kubeconfig
    required: false
  suspend-state:
    description: Cronjob desired state
    required: true
