version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "Europe/Bratislava"
    groups:
      all-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "Europe/Bratislava"
    groups:
      all-npm-dependencies:
        patterns:
          - "*"