version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "monthly"
      time: "10:00"
    assignees:
      - "maso7"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: "monthly"
      time: "10:00"
    assignees:
      - "maso7"
