name: Kubectl set addons replicas
description: Set addons replicas
author: Tomas Hulata <thulata@pixelfederation.com>
runs:
  using: node16
  main: main.js
inputs:
  directory:
    description: Working directory
    required: false
    default: "."
  namespace:
    description: K8s namespace to use
    required: true
  regexp:
    description: Regexp prefix to match addon deployment without addon name
    required: true
  kubeconfig:
    description: Path to kubeconfig
    required: false
  helm-values-file:
    description: Helm values file to get addons replicas count
    required: true
