name: E2e test workflow

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  kind:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- uses: engineerd/setup-kind@v0.5.0
      - uses: helm/kind-action@v1.8.0

      - name: Check cluster
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)

      - name: Deploy nginx
        run: |
          kubectl apply -f tests/demo-nginx.yaml
          kubectl wait pods -n default -l k8s-app=demo-nginx --for condition=Ready --timeout=300s
          kubectl -n default get pods

      - name: Get replicas
        id: get-replicas
        uses: ./get-replicas
        with:
          namespace: default
          regexp: ".*nginx.*"

      - name: Print replicas output
        run: |
          echo "${{ steps.get-replicas.outputs.replicas }}"

      - name: Set min replicas
        uses: ./set-min-replicas
        with:
          namespace: default
          regexp: ".*nginx.*"
          replicas: 2

      - name: Prefix ingress class
        uses: ./change-ingress-class
        with:
          namespace: default
          regexp: ".*nginx.*"
          class: tombo-
          mode: prefix

      - name: Strip ingress class
        uses: ./change-ingress-class
        with:
          namespace: echoheaders
          regexp: ".*nginx.*"
          class: tombo-
          mode: strip

      - name: Append ingress class
        uses: ./change-ingress-class
        with:
          namespace: echoheaders
          regexp: ".*nginx.*"
          class: -tombo
          mode: append

      - name: Replace ingress class
        uses: ./change-ingress-class
        with:
          namespace: echoheaders
          regexp: ".*nginx.*"
          class: nginx-external
          mode: replace
