name: E2e test workflow

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  kind:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #- uses: engineerd/setup-kind@v0.5.0
      - uses: helm/kind-action@v1.3.0

      - name: Check cluster
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)

      - name: Deploy nginx
        run: |
          kubectl apply -f tests/demo-nginx.yaml
          kubectl wait pods -n default -l k8s-app=demo-nginx --for condition=Ready --timeout=300s
          kubectl -n default get pods

      - name: Get min replicas
        id: get-min
        uses: pixelfederation/gh-action-kubectl/get-min-replicas@main
        with:
          namespace: default
          regexp: ".*nginx.*"

      - name: Print min replicas output
        run: |
          echo "${{ steps.get-min.outputs.replicas }}"
