name: Local devel workflow

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - pxfd-linux-amd64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault.kube.dev.pxfd.tech/
          method: kubernetes
          path: kubernetes_shared
          role: action-github-runner
          secrets: |
            secret/pxfd-shared-eks/action-runner-controller/runners_secrets kubeconfig_workload-dev | kubeconfig ;

      # Kubernetes config
      - name: Create kubernetes config
        shell: bash
        run: |
          mkdir -p /home/runner/.kube
          echo "${{ steps.secrets.outputs.kubeconfig }}" | base64 -d > /home/runner/.kube/config
          chmod 600 ~/.kube/config

      - name: Kubectl version
        id: kubectl-version
        run: |
          kubectl version && kubectl get ns

      - name: Get min replicas
        id: get-min
        uses: ./get-min-replicas
        with:
          namespace: echoheaders
          regexp: ".*echo.*"

      - name: Get the output
        run: |
          echo "${{ steps.get-min.outputs.replicas }}"
